

spring:
  datasource:
  # data source basic config
    username: root
    password: galland990531
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testmb?useSSL=FALSE&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
  # 数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  # 建表
  #  schema:
  #    - classpath:sql/department.sql
  #    - classpath:sql/employee.sql
  # springboot 2.1.5 and later version requires
    initialization-mode: always
server:
  port: 8899
